project:
  type: website
  output-dir: docs
  render: 
  - index.qmd
  - math-237-project_template.qmd

website:
  title: "Vivian's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: math-237-project_template.qmd
        text: "Rent Project"
format:
  html:
    theme: cosmo
    code-summary: "Show code"
    toc: true

editor: visual

